### ISSUE TITLE
http://www.biomart.org/biomart

### ISSUE THREAD

**Issue by jokerbea** [sebriois/biomart#15]
When you enter this address you get a 404 error, making package completely impossible to work with.
The only link working is this one:
http://useast.ensembl.org/biomart/martview
And it doesn't have the same attributes

**Comment by sebriois** [comment]
Hi,

I'm not sure I understand the actual issue.
Here is what I've tried:
```shell
>>> import biomart
>>> server = biomart.BiomartServer( "http://useast.ensembl.org/biomart" )
>>> server.is_alive
True
```
So, basically, I can connect to the URL you specified (without the trailing martview though).

Does this help?

**Comment by sebriois** [comment]
also, another user came accross errors related to attributes and provided fixed code that I've merged to my code.
Please update your package and let me know:
`pip install biomart --upgrade`

**Comment by jokerbea** [comment]
Hi could you tell me how it works please because I tried this:

from biomart import BiomartServer
server = BiomartServer( "http://useast.ensembl.org/biomart/martview" )
server.verbose = True
print server.show_databases()

And it still doesn't work
ᐧ

2016-04-07 9:15 GMT-04:00 Sébastien Briois <notifications@github.com>:

**Comment by sebriois** [comment]
please take a look at the code in my first comment and what the URL should look like. Basically, you need to remove the trailing /martview in your URL and it will work

**Comment by elmbeech** [comment]
hi @sebriois ,

i think the problem is the user instruction at pip: https://pypi.python.org/pypi/biomart/0.9.2
if you try to connect to the server as described there: 
```
from biomart import BiomartServer
server = BiomartServer( "http://www.biomart.org/biomart" )
```
you get a 404.

so the instructions should be changes to:
```
import biomart
server = biomart.BiomartServer( "http://useast.ensembl.org/biomart" )
```
thank you for writing this package.

best, 
Elmar

**Comment by winni2k** [comment]
I get this error as well. When I use the URL `http://www.ensembl.org/biomart`, then I can connect.

**Comment by Afollet** [comment]
> hi @sebriois ,
> 
> i think the problem is the user instruction at pip: https://pypi.python.org/pypi/biomart/0.9.2
> and i think this is taken from the README.md or README.txt.
> if you try to connect to the server as described there:
> 
> ```
> from biomart import BiomartServer
> server = BiomartServer( "http://www.biomart.org/biomart" )
> ```
> 
> you get a 404.
> 
> so the instructions should be changes to:
> 
> ```
> import biomart
> server = biomart.BiomartServer( "http://useast.ensembl.org/biomart" )
> ```
> 
> thank you for writing this module!
> 
> best,
> Elmar

Yes, I believe the documentation needs to be updated.
